# Generated by Django 4.0.5 on 2022-06-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_movie_table_alter_rating_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movieID',
            new_name='movieid',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='movieID',
            new_name='movieid',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='ratingID',
            new_name='ratingid',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='userID',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='userid',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
