name: Djangular Package and Deploy

on:
  push:
    branches:
      - alex-django-angular-test
  workflow_dispatch:
  
jobs: 
  test_ssh:
    runs-on: ubuntu-20.04
    name: copy private key from repo secret
    steps:
      - name: Create private key file
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
        run: |
          mkdir -p ~/.ssh
          cd ~/.ssh/
          echo "$SSH_KEY" > cs673-ssh-key.pem
          chmod 600 cs673-ssh-key.pem
          echo "$KNOWN_HOSTS" > known_hosts
          ssh -i "cs673-ssh-key.pem" ec2-user@44.199.212.24
          ls
      
      - name: delete private key file
        if: always()
        run: |
          sudo rm ~/.ssh/cs673-ssh-key.pem